import { Grid } from "@mui/material";
import Head from "next/head";
import LeftMainNav from "../components/LeftMainNav/LeftMainNav";

export default function Home() {
  return (
    <>
      <Head>
        <title>Tests reports</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Grid
        container
        style={{
          // width: "25vw",
          height: 400,
          // border: "1px solid blue",
          // background: "rgb(230, 230, 230)",
        }}
      >
        <Grid item xs={12}></Grid>
        <div
          style={{
            width: "20vw",
            minHeight: 400,
            margin: -8,
            // border: "1px solid blue",
            background: "rgb(230, 230, 230)",
            display: "flex",
            alignItems: "start",
            justifyContent: "center",
          }}
        >
          <LeftMainNav />
        </div>
        <div
          style={{
            width: "66vw",
            minHeight: 400,
            // margin: -8,
            padding: 20,
            // border: "1px solid blue",
            // background: "rgb(230, 230, 230)",
            display: "flex",
            textAlign: "center",
            // justifyContent: "center",
          }}
        >
          Welcome to Test-reports, Site for Test Reports, <br />
          <br />
          Want to hear more? Enter the About tab. <br />
          <br />
          Do you have permission? sign in with google and start working!
        </div>
      </Grid>
    </>
  );
}
